<?php

/**
 * @file
 * Contains lb_ux.module.
 */

use Drupal\lb_ux\Element\LayoutBuilderUX;

/**
 * Implements hook_element_plugin_alter().
 */
function lb_ux_element_plugin_alter(array &$definitions) {
  $definitions['layout_builder']['class'] = LayoutBuilderUX::class;
}

/**
 * Implements hook_preprocess_HOOK() for the list of layouts.
 */
function lb_ux_preprocess_item_list__layouts(&$variables) {
  $layout_manager = \Drupal::service('plugin.manager.core.layout');
  // Replace the icons with smaller versions.
  foreach (array_keys($variables['items']) as $layout_id) {
    if (isset($variables['items'][$layout_id]['value']['#title']['icon'])) {
      $definition = $layout_manager->getDefinition($layout_id);
      $variables['items'][$layout_id]['value']['#title']['icon'] = $definition->getIcon(60, 40, 1, 3);
    }
  }
}
