<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function bg_img_field_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // remove the cardinality container from the background image field
  if ($form_id === 'field_config_edit_form') {
    $field_widget_storage = $form_state->getStorage();
    $pluginId = $field_widget_storage['default_value_widget']->getPluginId();

    if ($pluginId === 'bg_img_field_widget') {
      unset($form["default_value"]);

    }
  }
}
